use slotmap::new_key_type;

new_key_type! {
    /// Identifies a live session within the farm; generated by `Nexus`.
    pub struct SessionKey;

    /// Identifies an active party; generated by `Nexus`.
    pub struct PartyKey;

    /// Identifies a group within a party; generated by `PartyActor`.
    pub struct GroupKey;
}

// Re-export slotmap types used throughout the crate.
pub use slotmap::{SecondaryMap, SlotMap};

/// Typed newtype around the wire-level worker slot index.
///
/// Using a dedicated type instead of a bare `usize` prevents accidentally
/// mixing up a slot index with any other `usize` value (e.g. task IDs).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct WorkerSlot(pub usize);
